#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# the 9th iteration, displays Best School and then Hi on a new line.
a=1
while [ $a -lt 11 ]; do
	echo "Best School"
	if [ $a  -eq 9  ]; then
	echo "Hi"
	fi
	((a++))
done
