#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
a=1
while [ $a -lt 13 ]
do
	b=1
	while [ $b -lt 60 ]
	do
		echo "$b"
		((b++))
	done
	echo "Hour: $a"
	((a++))
done
